import { BOARD_COLUMNS, BOARD_ROWS } from './board.js';

export const levels = [
  {
    id: 1,
    levelLabel: '第 1 关',
    title: '咪宝去哪儿了？',
    winTitle: '发现线索啦！',
    winMessage: '发现咪宝的小爪印啦，它好像往客厅深处去了。',
    rewardIcon: '猫爪.png',
    movementRule: 'none',
    tileSetSize: 24,
    rows: BOARD_ROWS,
    columns: BOARD_COLUMNS,
    timeLimitSeconds: 300,
    shuffleLimit: 4,
    hintLimit: 5,
  },
  {
    id: 2,
    levelLabel: '第 2 关',
    title: '线索变多啦',
    winTitle: '找到线索啦！',
    winMessage: '小鱼玩具掉在地毯边，咪宝刚才一定来过这里。',
    rewardIcon: '鱼.png',
    movementRule: 'none',
    tileSetSize: 28,
    rows: BOARD_ROWS,
    columns: BOARD_COLUMNS,
    timeLimitSeconds: 300,
    shuffleLimit: 4,
    hintLimit: 5,
  },
  {
    id: 3,
    levelLabel: '第 3 关',
    title: '上下分离',
    winTitle: '越来越近啦！',
    winMessage: '沙发下面好像有一点声音……咪宝可能躲在那里！',
    rewardIcon: '猫爬架.png',
    movementRule: 'splitUpDown',
    tileSetSize: 28,
    rows: BOARD_ROWS,
    columns: BOARD_COLUMNS,
    timeLimitSeconds: 300,
    shuffleLimit: 4,
    hintLimit: 5,
  },
  {
    id: 4,
    levelLabel: '第 4 关',
    title: '左右分离',
    winTitle: '快找到啦！',
    winMessage: '柜子旁边露出一点尾巴尖，咪宝真的在这里！',
    rewardIcon: '侦探咪宝.png',
    movementRule: 'splitLeftRight',
    tileSetSize: 28,
    rows: BOARD_ROWS,
    columns: BOARD_COLUMNS,
    timeLimitSeconds: 300,
    shuffleLimit: 4,
    hintLimit: 5,
  },
  {
    id: 5,
    levelLabel: '第 5 关',
    title: '地心引力',
    winTitle: '找到咪宝啦！',
    winMessage: '咪宝终于出来啦。今天也辛苦你啦！',
    rewardIcon: '开心咪宝.png',
    movementRule: 'gravityDown',
    tileSetSize: 28,
    rows: BOARD_ROWS,
    columns: BOARD_COLUMNS,
    timeLimitSeconds: 300,
    shuffleLimit: 4,
    hintLimit: 5,
  },
  {
    id: 6,
    levelLabel: '第 6 关',
    title: '向右看齐',
    winTitle: '方向对啦！',
    winMessage: '咪宝好像又往右边挪了一点。',
    rewardIcon: '咪宝抱树.png',
    movementRule: 'alignRight',
    goalType: 'clearBoard',
    tileSetSize: 28,
    rows: BOARD_ROWS,
    columns: BOARD_COLUMNS,
    timeLimitSeconds: 300,
    shuffleLimit: 4,
    hintLimit: 5,
  },
  {
    id: 7,
    levelLabel: '第 7 关',
    title: '天花板与地板的双向奔赴',
    winTitle: '靠近地平线啦！',
    winMessage: '上下的线索都聚到中间，咪宝越来越藏不住啦。',
    rewardIcon: '猫爪.png',
    movementRule: 'collapseToHorizon',
    goalType: 'clearBoard',
    tileSetSize: 28,
    shuffleBonus: 2,
    rows: BOARD_ROWS,
    columns: BOARD_COLUMNS,
    timeLimitSeconds: 300,
    shuffleLimit: 4,
    hintLimit: 5,
  },
  {
    id: 8,
    levelLabel: '第 8 关',
    title: '左右归中',
    winTitle: '回到中线啦！',
    winMessage: '左右两边的线索都靠过来了，咪宝就在附近！',
    rewardIcon: '迷惑咪宝.png',
    movementRule: 'collapseToCenterLine',
    goalType: 'clearBoard',
    tileSetSize: 28,
    shuffleBonus: 2,
    rows: BOARD_ROWS,
    columns: BOARD_COLUMNS,
    timeLimitSeconds: 300,
    shuffleLimit: 4,
    hintLimit: 5,
  },
  {
    id: 9,
    levelLabel: '第 9 关',
    title: '全部向心',
    winTitle: '找到咪宝啦！',
    winMessage: '所有线索都聚到中间，咪宝终于藏不住啦。',
    rewardIcon: '开心咪宝.png',
    movementRule: 'collapseToCenterCross',
    goalType: 'clearBoard',
    tileSetSize: 28,
    shuffleBonus: 2,
    rows: BOARD_ROWS,
    columns: BOARD_COLUMNS,
    timeLimitSeconds: 300,
    shuffleLimit: 4,
    hintLimit: 5,
  },
];
