import { BOARD_COLUMNS, BOARD_ROWS } from './board.js';

export const levels = [
  {
    id: 1,
    levelLabel: '第 1 关',
    title: '咪宝去哪儿了？',
    winTitle: '发现线索啦！',
    winMessage: '发现咪宝的小爪印啦，它好像往客厅深处去了。',
    rewardIcon: '猫爪.png',
    movementRule: 'none',
    tileSetSize: 24,
    rows: BOARD_ROWS,
    columns: BOARD_COLUMNS,
    timeLimitSeconds: 300,
    shuffleLimit: 4,
    hintLimit: 5,
  },
  {
    id: 2,
    levelLabel: '第 2 关',
    title: '线索变多啦',
    winTitle: '找到线索啦！',
    winMessage: '小鱼玩具掉在地毯边，咪宝刚才一定来过这里。',
    rewardIcon: '鱼.png',
    movementRule: 'none',
    tileSetSize: 28,
    rows: BOARD_ROWS,
    columns: BOARD_COLUMNS,
    timeLimitSeconds: 300,
    shuffleLimit: 4,
    hintLimit: 5,
  },
  {
    id: 3,
    levelLabel: '第 3 关',
    title: '上下分离',
    winTitle: '越来越近啦！',
    winMessage: '沙发下面好像有一点声音……咪宝可能躲在那里！',
    rewardIcon: '猫爬架.png',
    movementRule: 'splitUpDown',
    tileSetSize: 28,
    rows: BOARD_ROWS,
    columns: BOARD_COLUMNS,
    timeLimitSeconds: 300,
    shuffleLimit: 4,
    hintLimit: 5,
  },
  {
    id: 4,
    levelLabel: '第 4 关',
    title: '左右分离',
    winTitle: '快找到啦！',
    winMessage: '柜子旁边露出一点尾巴尖，咪宝真的在这里！',
    rewardIcon: '侦探咪宝.png',
    movementRule: 'splitLeftRight',
    tileSetSize: 28,
    rows: BOARD_ROWS,
    columns: BOARD_COLUMNS,
    timeLimitSeconds: 300,
    shuffleLimit: 4,
    hintLimit: 5,
  },
  {
    id: 5,
    levelLabel: '第 5 关',
    title: '地心引力',
    winTitle: '找到咪宝啦！',
    winMessage: '咪宝终于出来啦。今天也辛苦你啦！',
    rewardIcon: '开心咪宝.png',
    movementRule: 'gravityDown',
    tileSetSize: 28,
    rows: BOARD_ROWS,
    columns: BOARD_COLUMNS,
    timeLimitSeconds: 300,
    shuffleLimit: 4,
    hintLimit: 5,
  },
];
